plot_points <- list()
library(tools)
## Action list ----
action <- toTitleCase(c(rep("conclusion",8),
                        rep("none", 16),
                        rep("A Character is attacked in a non lethal way", 2),
                        "Collateral Damage",
                        rep("A Character is attacked in a lethal way", 2),
                        rep("Ambush", 2),
                        "Catastrophe",
                        "Character has a clever idea",
                        "Something is getting away",
                        rep("Hunted", 2),
                        "Distraction",
                        rep("A Character is attacked to abduct", 2),
                        "Something exotic",
                        rep("Immediately", 2),
                        rep("Chase", 2),
                        rep("Escape", 2),
                        rep("Heavily Guarded", 2),
                        rep("Rescue", 2),
                        rep("Physical contest of skills", 2),
                        rep("Mass Battle", 2),
                        "A crucial life support beings to fail",
                        rep("Victory!", 2),
                        rep("Taking chances", 2),
                        rep("Sole survivor", 2),
                        rep("Stop that", 2),
                        rep("Defend or not to defend", 2),
                        rep("Crash", 2),
                        rep("Physical barrier to overcome", 2),
                        rep("Double down", 2),
                        rep("Theft", 2),
                        rep("Dealing with a calamity", 2),
                        rep("Sudden cessation", 2),
                        rep("Used against them", 1),
                        rep("Travel setting", 1),
                        rep("Frenetic activity", 2),
                        rep("Sneaky barrier", 2),
                        rep("A moment of peace", 2),
                        rep("Beat you to it", 2),
                        rep("Confrontation", 2),
                        rep("Protector", 2),
                        rep("Crescendo", 2),
                        rep("Destroy the thing", 2)))


## Tension list ----
tension <- toTitleCase(c(rep("conclusion",8),
                         rep("none", 16),
                         rep("Into the Unknown", 2),
                         "A needed resource runs out",
                         rep("Impending doom", 1),
                         rep("A motive free crime", 1),
                         "Collateral damage",
                         rep("Shady places",2),
                         "Do it, or else",
                         "Remote location",
                         "Catastrophe",
                         "Grisly tone",
                         "Something is getting away",
                         rep("Retaliation", 2),
                         rep("A character disappears", 1),
                         rep("Hunted", 1),
                         rep("Bad decision", 1),
                         rep("Wanted by the law", 1),
                         rep("Something exotic", 1),
                         rep("Immediately", 1),
                         "Betrayal!",
                         rep("A character is incapacitated", 1),
                         rep("Nowhere to run", 1),
                         rep("At night", 2),
                         rep("A secret weapon", 1),
                         rep("Heavily guarded", 1),
                         rep("Dead", 1),
                         rep("Suspicion", 1),
                         rep("Lose lose", 1),
                         rep("Out in the open", 1),
                         rep("A character is diminished", 2),
                         rep("Enemies", 1),
                         rep("Menacing tone", 1),
                         rep("A crucial life system begins to fail", 1),
                         rep("Victory!", 1),
                         rep("Taking chances", 1),
                         rep("Sole survivor", 1),
                         rep("A problem returns", 2),
                         rep("Stuck", 2),
                         rep("Disarmed", 2),
                         rep("Quiet catastrophe", 1),
                         rep("Standoff", 1),
                         rep("Hidden threat", 1),
                         rep("A need to hide", 2),
                         rep("Followed", 2),
                         rep("It´s a trap!",2),
                         rep("Time limit",2),
                         rep("A needed resource is running short",2),
                         rep("Bad news",2),
                         rep("Hunker down", 1),
                         rep("Abandoned", 2),
                         rep("Used against them", 1),
                         rep("Creepy tone", 2),
                         rep("Travel setting",1),
                         rep("A new enemy", 1),
                         rep("Rural setting", 1),
                         rep("Vulnerability exploited",1)))

## Mystery list ----
mystery <- toTitleCase(c(rep("conclusion",8),
                         rep("none", 16),
                         rep("Into the unknown", 2),
                         rep("Useful information from an unknown source",2),
                         rep("A motive free crime", 2),
                         rep("A character disappears", 2),
                         "This isn´t working",
                         rep("A resource disappears", 2),
                         "Fortuitous find",
                         rep("All is revealed!", 1),
                         rep("Useful information from a known source", 2),
                         rep("Cryptic information from a known source", 1),
                         rep("Lie discovered", 2),
                         rep("Something exotic", 1),
                         rep("A crime is commited", 2),
                         rep("It´s a secret", 2),
                         rep("Something lost has been found", 1),
                         rep("The observer", 1),
                         rep("A secret weapon", 1),
                         rep("Liar!", 2),
                         "A character acts out of character",
                         rep("Dead", 1),
                         rep("Mystery solved", 2),
                         rep("Secret information leaked", 1),
                         rep("Suspicion", 2),
                         rep("Evidence", 2),
                         rep("The plot thickens", 2),
                         rep("Dubious rationale", 1),
                         rep("A crucial life support system begins to fail", 1),
                         rep("Cryptic information from an unknown source", 2),
                         rep("A common thread", 2),
                         rep("Not their master", 1),
                         rep("The secret to the power", 2),
                         rep("Hidden agenda", 2),
                         rep("An object of unknown use is found", 1),
                         rep("Clear the record", 1),
                         rep("Framed", 1),
                         rep("An improbable crime", 1),
                         rep("The hidden hand", 2),
                         rep("Find it or else", 2),
                         rep("Travel setting", 1),
                         rep("An old deal", 1),
                         rep("A mysterious new person", 1),
                         rep("Rural setting", 1),
                         rep("Someone is where they should not be", 2),
                         rep("Vulnerability exploited", 1),
                         rep("Fraud", 2),
                         rep("Beat you to it", 2),
                         rep("Conspiracy theory", 1),
                         rep("An opposing story", 1)))

## Social list ----
social <- toTitleCase(c(rep("conclusion",8),
                        rep("none", 16),
                        rep("Outcast", 2),
                        rep("sold!",2),
                        rep("Retaliation", 2),
                        rep("A high energy gathering", 1),
                        "A rare or unique social gathering",
                        rep("An organization",2),
                        "People behaving badly",
                        rep("Fame", 1),
                        "Scapegoat",
                        rep("The observer", 1),
                        "Liar!",
                        rep("Headquarters", 2),
                        rep("A common social gathering", 2),
                        rep("Light urban setting", 2),
                        rep("A work related gathering", 2),
                        rep("Suspicion", 1),
                        rep("Enemies", 1),
                        rep("Dense urban setting", 2),
                        rep("A group is in trouble", 2),
                        rep("Token response", 1),
                        rep("Not their master", 1),
                        rep("Public location", 2),
                        rep("The leader", 2),
                        rep("Savior", 2),
                        rep("Reinforcements", 2),
                        rep("Government", 2),
                        rep("Injustice", 2),
                        rep("A celebration", 2),
                        rep("Standoff", 1),
                        rep("Religion", 1),
                        rep("Innocent", 1),
                        rep("Preparation", 2),
                        rep("A meeting of minds", 1),
                        rep("Organizations in conflict", 1),
                        rep("Powerful person", 1),
                        rep("Travel setting", 1),
                        rep("Escort duty", 1),
                        rep("An Old Deal", 1),
                        rep("Alliance", 2),
                        rep("Power over others", 2),
                        rep("Rural setting", 1),
                        rep("Corruption",2),
                        rep("It´s business", 2),
                        rep("Just cause gone awry", 1),
                        rep("Confrontation", 1),
                        rep("Argument", 2),
                        rep("Social tension set to boiling", 1),
                        rep("Servant", 1)))

## Personal list ----
personal <- toTitleCase(c(rep("conclusion",8),
                          rep("none", 16),
                          rep("Persuasion", 2),
                          "Do it, or else",
                          rep("Retaliation", 1),
                          rep("Bad decision", 1),
                          rep("Ill will", 2),
                          rep("Wanted by the law",2),
                          rep("It is your duty", 2),
                          rep("Character connection severed", 2),
                          "Humiliation",
                          rep("Betrayal", 2),
                          rep("A character is incapacitated", 2),
                          rep("The observer", 1),
                          rep("Home sweet home", 2),
                          rep("Headquarters", 1),
                          rep("Family matters", 2),
                          rep("A figure from the past", 1),
                          rep("A character is diminished", 2),
                          rep("Enemies", 2),
                          "Doing the right thing",
                          rep("At your mercy", 2),
                          rep("Fall from power", 2),
                          rep("Help is offered, for a price", 2),
                          rep("Prized possession", 2),
                          rep("Disarmed", 1),
                          rep("It´s all about you", 2),
                          rep("Character connection", 2),
                          rep("Innocent", 1),
                          rep("Willing to talk", 2),
                          rep("Character harm", 2),
                          rep("Framed", 1),
                          rep("Preparation", 2),
                          rep("Friend focus", 1),
                          rep("Untouchable", 1),
                          rep("Bribe",1),
                          rep("Character assistance", 2),
                          rep("Asking for help", 2),
                          rep("Welcome to the plot", 1),
                          rep("Likeable", 1),
                          rep("The promise of reward", 2),
                          rep("Expert knowledge", 1),
                          rep("A focus on the mundane", 2),
                          rep("Run away!", 2),
                          rep("Protector", 2),
                          rep("Servant", 2)))

## Data frame creation ----
plot_points$df <- data.frame(action,tension,mystery,social,personal)
rm(list = c("action", "tension", "mystery", "social", "personal"))
plot_points$meta <- toTitleCase(c(rep("Character exits the adventure", 18),
                                  rep("Character returns", 9),
                                  rep("Character steps up", 9),
                                  rep("Character steps down", 19),
                                  rep("Character downgrade", 18),
                                  rep("Character upgrade", 9),
                                  rep("Plotline combo", 18)))
